# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "a96653813f308aee3e487ca8f002e9b2"
name = "dhl-api"
handle = "dhl-api-4"
application_url = "https://dealers-bent-bits-bernard.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "testtakewithfood.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_draft_orders,write_orders"

[auth]
redirect_urls = [
  "https://dealers-bent-bits-bernard.trycloudflare.com/auth/callback",
  "https://dealers-bent-bits-bernard.trycloudflare.com/auth/shopify/callback",
  "https://dealers-bent-bits-bernard.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

[pos]
embedded = false
