# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "9706456a83821e1dd659e931088e8b93"
name = "dhl-api"
handle = "dhl-api-1"
application_url = "https://reduces-wales-middle-href.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "tanya-soni.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_draft_orders,write_orders"

[auth]
redirect_urls = [
  "https://reduces-wales-middle-href.trycloudflare.com/auth/callback",
  "https://reduces-wales-middle-href.trycloudflare.com/auth/shopify/callback",
  "https://reduces-wales-middle-href.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

[pos]
embedded = false
