# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "5c764bacb88ec972c016fac4ca6182bc"
name = "dhl-api"
handle = "dhl-api-5"
application_url = "https://exercise-nebraska-hydrogen-submission.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "quickstart-9dd3668a.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_draft_orders,write_orders"

[auth]
redirect_urls = [
  "https://exercise-nebraska-hydrogen-submission.trycloudflare.com/auth/callback",
  "https://exercise-nebraska-hydrogen-submission.trycloudflare.com/auth/shopify/callback",
  "https://exercise-nebraska-hydrogen-submission.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

[pos]
embedded = false
